services:
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"

  opa:
    image: openpolicyagent/opa:0.70.0-static
    command:
      - "run"
      - "--server"
      - "--addr=0.0.0.0:8181"
      - "--log-level=error"
      - "/policy/authz.rego"
      - "/policy/bundle.json"
    ports:
      - "8181:8181"
    volumes:
      - ../policy/gateway/authz.rego:/policy/authz.rego:ro
      - ./opa/bundle.json:/policy/bundle.json:ro
